package Recursion;

//QUES Given a string, we have to find out all subsequences of it.
//A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

public class SubsequenceString {
    public static void main(String[] args) {

        String str = "abc";

        subsequence(str,0,"");
    }

    static void subsequence(String str, int idx, String newString){

        if(idx == str.length()){
            System.out.println(newString);
            return;
        }

        //there will be 2 possibility that the char will be added or not
        char currChar = str.charAt(idx);

        //to be
        subsequence(str,idx+1,newString+currChar);

        //or not to be
        subsequence(str,idx+1,newString);

    }
}
